/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.cmjd.layered.view;

import hotel.cmjd.layered.controller.GuestController;
import hotel.cmjd.layered.controller.PackageController;
import hotel.cmjd.layered.controller.ReservationController;
import hotel.cmjd.layered.controller.RoomController;
import hotel.cmjd.layered.dto.GuestDto;
import hotel.cmjd.layered.dto.PackageDto;
import hotel.cmjd.layered.dto.ReservationDto;
import hotel.cmjd.layered.dto.RoomDto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenulfernando
 */
public class ReservationView extends javax.swing.JFrame {

    private GuestController guestController;
    private RoomController roomController;
    private PackageController packageController;
    private ReservationController reservationController;

    /**
     * Creates new form ReservationView
     */
    public ReservationView() {
        guestController = new GuestController();
        roomController = new RoomController();
        packageController = new PackageController();
        reservationController = new ReservationController();
        initComponents();
        loadReservationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblResevation1 = new javax.swing.JTable();
        txtRoomPrice = new javax.swing.JTextField();
        lblPackPrice = new java.awt.Label();
        lblRoomNo = new java.awt.Label();
        txtRoomNo = new javax.swing.JTextField();
        btnSearchRoom = new javax.swing.JButton();
        btnSearchGuest = new javax.swing.JButton();
        txtGuestId = new javax.swing.JTextField();
        lblGuestId = new java.awt.Label();
        lblReservId = new java.awt.Label();
        txtReservId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPackId = new javax.swing.JTextField();
        txtPackPrice = new javax.swing.JTextField();
        btnSearchPackage = new javax.swing.JButton();
        lblPackId = new java.awt.Label();
        txtCheckIn = new javax.swing.JTextField();
        btnPlaceReservation = new javax.swing.JButton();
        lblCheckIn = new java.awt.Label();
        lblCheckOut = new java.awt.Label();
        txtCheckOut = new javax.swing.JTextField();
        lblPackageData = new javax.swing.JLabel();
        lblGuestData = new javax.swing.JLabel();
        lblRoomData = new javax.swing.JLabel();
        lblRoomPrice = new java.awt.Label();
        btnDeleteReservation = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblReservation = new javax.swing.JTable();
        btnCheckout = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();

        tblResevation1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblResevation1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRoomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomPriceActionPerformed(evt);
            }
        });

        lblPackPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPackPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblPackPrice.setText("Package Price:");

        lblRoomNo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomNo.setForeground(new java.awt.Color(0, 0, 0));
        lblRoomNo.setText("Room No :");

        txtRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNoActionPerformed(evt);
            }
        });

        btnSearchRoom.setText("Search");
        btnSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRoomActionPerformed(evt);
            }
        });

        btnSearchGuest.setLabel("Search");
        btnSearchGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchGuestMouseClicked(evt);
            }
        });
        btnSearchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGuestActionPerformed(evt);
            }
        });

        txtGuestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuestIdActionPerformed(evt);
            }
        });

        lblGuestId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblGuestId.setForeground(new java.awt.Color(0, 0, 0));
        lblGuestId.setText("Guest Id :");

        lblReservId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservId.setForeground(new java.awt.Color(0, 0, 0));
        lblReservId.setText("Reservation Id :");

        txtReservId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservIdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservation");

        txtPackId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackIdActionPerformed(evt);
            }
        });

        txtPackPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackPriceActionPerformed(evt);
            }
        });

        btnSearchPackage.setText("Search");
        btnSearchPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPackageActionPerformed(evt);
            }
        });

        lblPackId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPackId.setForeground(new java.awt.Color(0, 0, 0));
        lblPackId.setText("Package Id:");

        txtCheckIn.setToolTipText("yyyy-MM-dd");
        txtCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInActionPerformed(evt);
            }
        });

        btnPlaceReservation.setLabel("Place Reservation");
        btnPlaceReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceReservationActionPerformed(evt);
            }
        });

        lblCheckIn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCheckIn.setForeground(new java.awt.Color(0, 0, 0));
        lblCheckIn.setText("Check In :");

        lblCheckOut.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCheckOut.setForeground(new java.awt.Color(0, 0, 0));
        lblCheckOut.setText("Check Out :");

        txtCheckOut.setToolTipText("yyyy-MM-dd");
        txtCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckOutActionPerformed(evt);
            }
        });

        lblRoomPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblRoomPrice.setText("Room Price :");

        btnDeleteReservation.setText("Delete Reservation");
        btnDeleteReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReservationActionPerformed(evt);
            }
        });

        tblReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservationMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblReservation);

        btnCheckout.setText("CheckOut");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReservId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPackId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPackId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSearchRoom)
                                            .addComponent(btnSearchPackage)))
                                    .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRoomData, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(193, 193, 193)
                                        .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(lblPackageData, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(lblPackPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPackPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtReservId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(68, 68, 68)
                                                .addComponent(lblGuestId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtGuestId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSearchGuest)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblGuestData, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMainMenu)))))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPlaceReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(37, Short.MAX_VALUE))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1532, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(lblReservId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGuestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtReservId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuestData, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSearchGuest)
                                .addComponent(txtGuestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnMainMenu)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchRoom))
                        .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoomData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoomNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPackId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPackId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSearchPackage)))
                                    .addComponent(lblPackageData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPackPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtPackPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceReservation)
                    .addComponent(btnDeleteReservation)
                    .addComponent(btnCheckout))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(708, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomPriceActionPerformed

    private void txtRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNoActionPerformed

    private void btnSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRoomActionPerformed
        searchRoom();
    }//GEN-LAST:event_btnSearchRoomActionPerformed

    private void btnSearchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGuestActionPerformed
        searchGuest();
    }//GEN-LAST:event_btnSearchGuestActionPerformed

    private void txtGuestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuestIdActionPerformed

    private void txtReservIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservIdActionPerformed

    private void txtPackIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPackIdActionPerformed

    private void txtPackPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPackPriceActionPerformed

    private void btnSearchPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPackageActionPerformed
        searchPackage();
    }//GEN-LAST:event_btnSearchPackageActionPerformed

    private void txtCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInActionPerformed

    private void btnPlaceReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceReservationActionPerformed
        placeReservation();
    }//GEN-LAST:event_btnPlaceReservationActionPerformed

    private void txtCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOutActionPerformed

    private void btnDeleteReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReservationActionPerformed
        deleteReservation();
    }//GEN-LAST:event_btnDeleteReservationActionPerformed

    private void btnSearchGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchGuestMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchGuestMouseClicked

    private void tblReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservationMouseClicked
        searchReservation();
    }//GEN-LAST:event_tblReservationMouseClicked

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        checkOut();
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
       new AppInitializerView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDeleteReservation;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnPlaceReservation;
    private javax.swing.JButton btnSearchGuest;
    private javax.swing.JButton btnSearchPackage;
    private javax.swing.JButton btnSearchRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label lblCheckIn;
    private java.awt.Label lblCheckOut;
    private javax.swing.JLabel lblGuestData;
    private java.awt.Label lblGuestId;
    private java.awt.Label lblPackId;
    private java.awt.Label lblPackPrice;
    private javax.swing.JLabel lblPackageData;
    private java.awt.Label lblReservId;
    private javax.swing.JLabel lblRoomData;
    private java.awt.Label lblRoomNo;
    private java.awt.Label lblRoomPrice;
    private javax.swing.JTable tblReservation;
    private javax.swing.JTable tblResevation1;
    private javax.swing.JTextField txtCheckIn;
    private javax.swing.JTextField txtCheckOut;
    private javax.swing.JTextField txtGuestId;
    private javax.swing.JTextField txtPackId;
    private javax.swing.JTextField txtPackPrice;
    private javax.swing.JTextField txtReservId;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtRoomPrice;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txtReservId.setText("");
        txtGuestId.setText("");
        txtRoomNo.setText("");
        lblRoomData.setText("");
        txtPackId.setText("");
        lblPackageData.setText("");
        txtRoomPrice.setText("");
        txtPackPrice.setText("");
        txtCheckIn.setText("");
        txtCheckOut.setText("");
    }

    private void searchGuest() {
        try {
            String guestId = txtGuestId.getText();
            GuestDto guestDto = guestController.getGuest(guestId);

            if (guestDto != null) {
                lblGuestData.setText(guestDto.getGuestFirstName() + " " + guestDto.getGuestLastName());
            } else {
                JOptionPane.showMessageDialog(this, "Guest Not Found");
            }

        } catch (Exception ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void placeReservation() {

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(new Date());
        ReservationDto dto = new ReservationDto();
        dto.setResvId(txtReservId.getText());
        dto.setGuestId(txtGuestId.getText());
        dto.setRoomNumber(txtRoomNo.getText());
        dto.setPackId(txtPackId.getText());
        dto.setRoomPrice(Double.parseDouble(txtRoomPrice.getText()));
        dto.setPackPrice(Double.parseDouble(txtPackPrice.getText()));
        dto.setResvDate(date);
        dto.setCheckInDate(txtCheckIn.getText());
        dto.setCheckOutDate(txtCheckOut.getText());
        try {
            String resp = reservationController.placeReservation(dto);
            JOptionPane.showMessageDialog(this, resp);
            clear();
            loadReservationTable();
        } catch (Exception ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }

    private void searchRoom() {

        try {
            String roomNo = txtRoomNo.getText();
            RoomDto roomDto = roomController.getRoom(roomNo);
            if (roomDto != null) {
                lblRoomData.setText(roomDto.getRoomType() + " | " + roomDto.getRoomPrice() + " | " + roomDto.getRoomStatus());
            } else {
                JOptionPane.showMessageDialog(this, "Room Not Found");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void searchPackage() {

        try {
            String packId = txtPackId.getText();
            PackageDto packageDto = packageController.getPackage(packId);
            if (packageDto != null) {
                lblPackageData.setText(packageDto.getPackName() + " | " + packageDto.getPackPrice());
            } else {
                JOptionPane.showMessageDialog(this, "Package Not Found");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void searchReservation() {
        String resvId = tblReservation.getValueAt(tblReservation.getSelectedRow(), 0).toString();

        try {
            ReservationDto dto = reservationController.getReservation(resvId);

            if (dto != null) {
                txtReservId.setText(dto.getResvId());
                txtGuestId.setText(dto.getGuestId());
                txtRoomNo.setText(dto.getRoomNumber());
                txtPackId.setText(dto.getPackId());
                txtRoomPrice.setText(Double.toString(dto.getRoomPrice()));
                txtPackPrice.setText(Double.toString(dto.getPackPrice()));
                txtCheckIn.setText(dto.getCheckInDate());
                txtCheckOut.setText(dto.getCheckOutDate());
            } else {
                JOptionPane.showMessageDialog(this, "Reservation  Not Found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void checkOut() {
        try {
            String roomNo = txtRoomNo.getText();

            String resp = roomController.reUpdateStatus(roomNo);
            JOptionPane.showMessageDialog(this, resp);
            loadReservationTable();
            clear();
        } catch (Exception ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void loadReservationTable() {
        try {
            String columns[] = {"Reserv Id", "Guest Id", "RoomNo", "Package Id", " Check In", "Check Out", "Price"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };

            tblReservation.setModel(dtm);

            List<ReservationDto> reservationDtos = reservationController.getAllReservation();

            for (ReservationDto reservationDto : reservationDtos) {
                Object[] rowData = {reservationDto.getResvId(), reservationDto.getGuestId(), reservationDto.getRoomNumber(), reservationDto.getPackId(), reservationDto.getCheckInDate(), reservationDto.getCheckOutDate(), reservationDto.getPrice()};
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(hotel.cmjd.layered.view.ReservationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void deleteReservation() {
        try {
            String resvId = txtReservId.getText();
            String roomNo = txtRoomNo.getText();

            String resp = reservationController.deleteReservation(resvId, roomNo);
            JOptionPane.showMessageDialog(this, resp);
            clear();
            loadReservationTable();
        } catch (Exception ex) {
            Logger.getLogger(ReservationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }
}
